---

- name: install postgresql installation pre requisites
  ansible.builtin.apt:
    name:
    - apt-transport-https
    - curl
    - ca-certificates

- name: install postgresql server
  ansible.builtin.apt:
    name:
    - postgresql-{{ postgresql.version }}
    state: present
    update_cache: yes
