---

package:
  version: 32.0.3
  whiteboard:
    version: 1.5.0
  appsToRestore:
  - 'bookmarks'
  - 'spreed'
  - 'deck'
  - 'mail'
  - 'notes'
  - 'contacts'
  - 'tasks'
  - 'drawio'
  - 'whiteboard'
  - 'richdocuments'
  appsToInstall:
  - 'bookmarks'
  - 'spreed'
  - 'deck'
  - 'mail'
  - 'notes'
  - 'contacts'
  - 'tasks'
  - 'drawio'