---

package:
  version: 33.0.0
  whiteboard:
    version: 1.5.7
  appsToRestore:
  - 'bookmarks'
  - 'spreed'
  - 'deck'
  - 'mail'
  - 'notes'
  - 'contacts'
  - 'tasks'
  - 'drawio'
  - 'whiteboard'
  - 'richdocuments'
  - 'forms'
  - 'calendar'
  - 'files_bpm'
  appsToInstall:
  - 'bookmarks'
  - 'spreed'
  - 'deck'
  - 'mail'
  - 'notes'
  - 'contacts'
  - 'tasks'
  - 'drawio'
  - 'forms'
  - 'calendar'
  - 'files_bpm'
