---

# vars for environment
redmine_unsecured: false

firewall_enabled: enabled

server:
  disk:
    mainDevice: '/dev/vda2'
  domain:
    main: meallier.fr
    sub: test.
    contact: eric@meallier.fr
  timezone: Europe/Paris
  countrycode: FR