---

# vars for environment
redmine_unsecured: true

firewall_enabled: disabled

server:
  disk:
    mainDevice: '/dev/sda1'
  domain:
    main: meallier.fr
    sub: test.
    contact: eric@meallier.fr
  timezone: Europe/Paris
  countrycode: FR
