---
- name: Update DNS
  ansible.builtin.include_role:
    name: update_infomaniak_dns
  vars:
    update_infomaniak_dns_target_extension: '{{ spliit.domain.suffix }}'
    update_infomaniak_dns_target_ip: '{{ ansible_default_ipv4.address }}'
  when: not redmine_unsecured

- name: Is already installed ?
  ansible.builtin.stat:
    path: "/opt/spliit/.env"
  register: already_installed

- name: Create dedicated database
  ansible.builtin.include_role:
    name: pg_new_fresh_database
  vars:
    pg_new_fresh_database_pg_username: '{{ dbschema.spliit.username }}'
    pg_new_fresh_database_pg_password: '{{ dbschema.spliit.password }}'
    pg_new_fresh_database_pg_database: '{{ dbschema.spliit.database }}'
  when: not already_installed.stat.exists is defined or not already_installed.stat.exists

- name: Ensure group "spliit" exists
  ansible.builtin.group:
    name: spliit
    state: present

- name: Add the user 'spliit'
  ansible.builtin.user:
    name: spliit
    group: spliit

- name: Download spliit files
  ansible.builtin.get_url:
    url: https://github.com/spliit-app/spliit/archive/refs/tags/{{ package.version }}.tar.gz
    dest: '/tmp/spliit-{{ package.version }}.tar.gz'
    timeout: 30

- name: Extract spliit files into /opt
  ansible.builtin.unarchive:
    src: '/tmp/spliit-{{ package.version }}.tar.gz'
    dest: /opt
    remote_src: 'yes'
    owner: spliit
    group: spliit

- name: Link to current version
  ansible.builtin.file:
    src: /opt/spliit-{{ package.version }}
    dest: /opt/spliit
    state: 'link'
    owner: 'spliit'
    group: 'spliit'

- name: Copy database configuration file
  ansible.builtin.template:
    src: env
    dest: /opt/spliit/.env
    owner: spliit
    group: spliit
    mode: '0644'

- name: Retrieve dependencies
  ansible.builtin.shell:
    cmd: '/usr/bin/npm install'
    chdir: '/opt/spliit'

- name: Build application
  ansible.builtin.shell:
    cmd: '/usr/bin/npm run build'
    chdir: '/opt/spliit'

- name: Open acces to .next folder
  ansible.builtin.shell: chmod -R 777 /opt/spliit/.next

- name: Install spliit service script
  ansible.builtin.copy:
    src: spliit.service
    dest: /etc/systemd/system/spliit.service
    owner: root
    group: root
    mode: '0644'

- name: Spliit service reload/start
  ansible.builtin.systemd:
    name: 'spliit'
    daemon_reload: true
    state: restarted
    enabled: true

- name: Is certificate already installed ?
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ spliit.domain.suffix }}.{{ server.domain.sub }}{{ server.domain.main }}/fullchain.pem"
  register: cert_already_installed

- name: Generate spliit certificate
  ansible.builtin.shell: /usr/bin/certbot certonly -d {{ spliit.domain.suffix }}.{{ server.domain.sub }}{{ server.domain.main }} -m {{ server.domain.contact }} --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html --keep-until-expiring --non-interactive
  when: not redmine_unsecured and not cert_already_installed.stat.exists

# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  ansible.builtin.template:
    src: spliit.conf
    dest: /opt/nginx/conf/server/spliit.conf

- name: Nginx service restart with full configuration
  ansible.builtin.systemd:
    name: 'nginx'
    state: restarted

- name: Cleanup installation
  ansible.builtin.file:
    path: '/tmp/spliit-{{ package.version }}.tar.gz'
    state: 'absent'
