---

- name: Update DNS
  ansible.builtin.include_role:
    name: update_infomaniak_dns
  vars:
    update_infomaniak_dns_target_extension: '{{ monitor.domain.suffix }}'
    update_infomaniak_dns_target_ip: '{{ ansible_default_ipv4.address }}'
  when: not redmine_unsecured

- name: Install netdata pre requisites
  ansible.builtin.apt:
    name:
      - lsb-release
      - curl
      - gpg
    state: present

- name: Download netdata installation script
  ansible.builtin.get_url:
    url: https://get.netdata.cloud/kickstart.sh
    dest: '/tmp/netdata-kickstart.sh'
    owner: root
    group: root
    mode: '0755'

- name: Installation script launch
  ansible.builtin.shell: '/tmp/netdata-kickstart.sh --stable-channel --non-interactive --native-only --dont-wait'

- name: Cleanup installation script
  ansible.builtin.file:
    path: '/tmp/netdata-kickstart.sh'
    state: 'absent'

- name: generate monitor certificate
  ansible.builtin.shell: /usr/bin/certbot certonly -d {{ monitor.domain.suffix }}.{{ server.domain.sub }}{{ server.domain.main }} -m {{ server.domain.contact }} --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html --keep-until-expiring --non-interactive
  when: not redmine_unsecured

# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  ansible.builtin.template:
    src: monitor.conf
    dest: /opt/nginx/conf/server/monitor.conf
    owner: root
    group: root
    mode: '0600'

- name: Nginx service restart with full configuration
  ansible.builtin.systemd:
    name: 'nginx'
    state: restarted
