---

- name: Stop applications
  ansible.builtin.systemd:
    name: '{{ service_name }}'
    state: stopped
  loop:
  - 'nginx.service'
  - 'gogs'
  loop_control:
    loop_var: service_name
  ignore_errors: true
  register: ignore_errors_register

- name: Restore database Gogs
  ansible.builtin.include_role:
    name: pg_restore_database
  vars:
    pg_restore_database_pg_filename: 'gogs-last.dmp'
    pg_restore_database_pg_username: '{{ dbschema.gogs.username }}'
    pg_restore_database_pg_database: '{{ dbschema.gogs.database }}'

- name: Restore files from pcloud Gogs
  ansible.builtin.include_role:
    name: pcloud_restore_file
  vars:
    pcloud_restore_file_foldername: '/data/gogs-repositories'
    pcloud_restore_file_filename: 'gogs-last-data.tar'

- name: Uncompress data Gogs
  ansible.builtin.unarchive:
    src: '/data/gogs-repositories/gogs-last-data.tar'
    dest: '/'
    remote_src: 'yes'
    owner: gogs
    group: gogs

- name: Remove old archive Gogs
  ansible.builtin.file:
    path: '/data/gogs-repositories/gogs-last-data.tar'
    state: 'absent'

- name: Restart applications
  ansible.builtin.systemd:
    name: '{{ service_name }}'
    state: started
  loop:
  - 'gogs'
  - 'nginx.service'
  loop_control:
    loop_var: service_name
