---

- name: Stop applications
  ansible.builtin.systemd:
    name: '{{ service_name }}'
    state: stopped
  loop:
  - 'nginx.service'
  loop_control:
    loop_var: service_name
  ignore_errors: true
  register: ignore_errors_register

- name: Restore database Redmine
  ansible.builtin.include_role:
    name: pg_restore_database
  vars:
    pg_restore_database_pg_filename: 'redmine-last.dmp'
    pg_restore_database_pg_username: '{{ dbschema.redmine.username }}'
    pg_restore_database_pg_database: '{{ dbschema.redmine.database }}'

- name: migrate redmine database
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; RAILS_ENV=production bin/rake db:migrate
  args:
    chdir: '/opt/redmine/'
  become_user: redmine

- name: Restore files from pcloud Redmine
  ansible.builtin.include_role:
    name: pcloud_restore_file
  vars:
    pcloud_restore_file_foldername: '/data/redmine-files'
    pcloud_restore_file_filename: 'redmine-last-files.tar'

- name: Uncompress data Redmine
  ansible.builtin.unarchive:
    src: '/data/redmine-files/redmine-last-files.tar'
    dest: '/'
    remote_src: 'yes'
    owner: nobody
    group: nogroup

- name: Remove old archive Redmine Redmine
  ansible.builtin.file:
    path: '/data/redmine-files/redmine-last-files.tar'
    state: 'absent'

- name: Restart applications
  ansible.builtin.systemd:
    name: '{{ service_name }}'
    state: started
  loop:
  - 'nginx.service'
  loop_control:
    loop_var: service_name
