---

- name: Stop applications
  systemd:
    name: '{{ service_name }}'
    state: stopped
  loop:
  - 'nginx.service'
  - 'gitea'
  loop_control:
    loop_var: service_name
  ignore_errors: True

- name: Restore database gitea
  include_role:
    name : pg_restore_database
  vars:
    pg_filename: 'gitea-last.dmp'
    pg_username: '{{ dbschema.gitea.username }}'
    pg_database: '{{ dbschema.gitea.database }}'

- name: Restore files from pcloud gitea
  include_role:
    name : pcloud_restore_file
  vars:
    foldername: '/data/gitea'
    filename: 'gitea-last-data.tar'

- name: Uncompress data gitea
  unarchive:
    src: '/data/gitea/gitea-last-data.tar'
    dest: '/'
    remote_src: 'yes'
    owner: gitea
    group: gitea

- name: Remove old archive gitea
  file:
    path: '/data/gitea/gitea-last-data.tar'
    state: 'absent'

- name: Restart applications
  systemd:
    name: '{{ service_name }}'
    state: started
  loop:
  - 'gitea'
  - 'nginx.service'
  loop_control:
    loop_var: service_name

