---

- name: Stop applications
  ansible.builtin.systemd:
    name: '{{ service_name }}'
    state: stopped
  loop:
  - 'nginx.service'
  - 'gitea'
  loop_control:
    loop_var: service_name
  ignore_errors: True
  register: ignore_errors_register

- name: Restore database gitea
  ansible.builtin.include_role:
    name: pg_restore_database
  vars:
    pg_restore_database_pg_filename: 'gitea-last.dmp'
    pg_restore_database_pg_username: '{{ dbschema.gitea.username }}'
    pg_restore_database_pg_database: '{{ dbschema.gitea.database }}'

- name: Restore files from pcloud gitea
  ansible.builtin.include_role:
    name: pcloud_restore_file
  vars:
    pcloud_restore_file_foldername: '/data/gitea'
    pcloud_restore_file_filename: 'gitea-last-data.tar'

- name: Uncompress data gitea
  ansible.builtin.unarchive:
    src: '/data/gitea/gitea-last-data.tar'
    dest: '/'
    remote_src: 'yes'
    owner: gitea
    group: gitea

- name: Remove old archive gitea
  ansible.builtin.file:
    path: '/data/gitea/gitea-last-data.tar'
    state: 'absent'

- name: Restart applications
  ansible.builtin.systemd:
    name: '{{ service_name }}'
    state: started
  loop:
  - 'gitea'
  - 'nginx.service'
  loop_control:
    loop_var: service_name
