---
# vars for environment


# vars for environment
redmine_unsecured: true

firewall_enabled: enabled

php:
  version: 8.4

postgresql:
  version: 18

ruby:
  version: 3.4.7
  reducedversion: 3.4.0

server:
  disk:
    mainDevice: '/dev/sda1'
  domain:
    main: meallier.fr
    sub:
    contact: eric@meallier.fr
  timezone: Europe/Paris
  countrycode: FR
