$ANSIBLE_VAULT;1.2;AES256;user
31323834636164303431643831303036363165323130353738393265376436643038323462656239
3536366232353161343831623836346334383066633561660a626564336162323739396431326465
39373966356635353533323036313933393564333331336462373461346636633561383134393565
3338636337393764610a636635356336616334396336303336303961363237343662366539333635
34323232323238656637356138663162653262666539626461313135616131376239636538646534
33396361333832336534313931396238313066333165386463623435373739336662636338653837
36643839393132646530343037663936303464396565303138393665633534376430353338326131
31653864636665346531393464643734396235646365306531366563323765613938633939656466
30646134333634616566313863633562336265643331316233386137396637313839346663383064
33633664303438336365636563333638663032396166313535333862356266636231356435643830
36643962386165653665623932336636663138653763306234306436333230356532623766356337
37636434383536356339313762376261333366353365303934343330623463313137336138386262
37646239373765326538373732356330643032393130373037373734326232363535386663383337
63633239396338623033386139663631616464336437303865366431353837313133356363306634
38346338663662393064326464353339363635343865633363313835356235386431393435623934
65316563316133313864653963343936623635343561653731396332663530643163326462643762
37336331616432346462373331303639303561623634643931666166653563356536383435313432
62646265393135356634356363666637396266613663363663316334663465656236356130646162
61663863353166306238633936323835313462643762343862383064636139613962663139393838
36323538353064633239653237626635343565366462663131326637663462356431633366653734
38326665393733336236346361623463363537376161633065393437653736356463653665313963
32343164303365626635633436626461373039616233623830613433383432356530326437643337
64303963613461316130663266643961376330353733303662353432383363313130396331336338
31653831306238366164393632636462373861656536616562393030636430626636313931353739
39303138346331306635616666613535363836633236333633393363643330373431626233613034
37633030326565343038366637646133353862303838646632336238646662316563336636623437
33353830396663393563646534633163356637306264653032303232626364643464393763346662
64386330396165313265656333303638386339316632356232626464323835353939393161373536
30656437383230316138373834346430393338613938303131343236646631613764616238316233
35666638646161383831636330646634643239333262306230323861633232336238313133633662
31343839333434383664613362323466313333346365326132653635356565313362633865663431
66383164346430663033313665663463326333613539326239623261323139643761653333366465
62313636353334326531633461336264633233386264313463373230373366323435633961623033
39616231626134643935333739346161393234373762616638616330336531646539323739323732
65366632333839653336373331313765323666316637356365656532643362373562656264303663
35653963366234386335663266386461363138333763643837303239343763626231363231306364
32313930363164636431656265333836333732613832313061663530353138326466313662656464
63373832626331643139356430343266326262623437666437643265663838316231646631373964
33633831653264326233666462343134373862616135313463353264393137653336333239666462
61663134363836396535613733383737323662333466396663626366366530663633323966663439
65613136643566323337323031643362313165333030343566396232373161386235646233343666
64313131393661323664626530353633343064626265663966363337323137343761316661313934
32643035626232396233366636633432306237663236616261343837613962626161653864366665
33623335346533633762653430643331316661356630373333653966326536306533346133626463
39336439336561303939376439323062353032616366313730386433336332393839613339376662
35646331623964333133343762333662323639356232633038326363356364643238396365613231
33663164343734636361336162393837393766373437343134623730323238363236333564633232
37323331303733666163656331386239313233636366633633333963316431346662613338356132
30363962306432353637313264306435653832333232323835613631363231653536396162343762
31643735336630383965616262353161313836656464616435653033386536373162396332313438
62306538366336643630376433666436643933393438333631356535333931653738363136653436
37306631626562393665663064353035386166616137303631396633336432363235656337383766
31353532363463616666613732323637666534663231653861366133303233373666623335383463
36343561386264306161363030356237363733633530323137633736306366313065333463363466
61303034633633626165306564383236353631353361666335373461633064373930363039633632
65643338376662656362653662373232386137373561346364386162363731636564306236663338
33316639383066346438616262336536396562613566353362623539313762386230653030623065
37623161633634646439383032363763623364613464333565653466333534636133353032356232
66313462333961373362646439303664303935373337386163383730613466663864306364383938
38646439326335313137626634346239313863623935653763396262663137353332303537333061
66313161666263396537366535626361643830623730643330386564646330633737653835666538
31363237363831396539343139323636333665386430373165356561356661343832376138316533
61316662313961663936616530306165343265346665616639663436653830346463393665636130
35666261653032643134363530383565326133383731633631313561336465343361333566343366
62336234663434346335653935333161376131313434363231313765613466633233346438366134
32313538373161656636303033376263643863386639376461323964663437663632616464316163
38656437303263613937666366343564656536326333363432353065653736333338313561623762
61363830333861643862666132663635633734323339356234373065623261343131376463366632
65323466623439313235633632306337346135613563643534653435373463643465396638386139
65306131346133356536303636333239393639343239373732323938336130626233343861376330
33313366373465323532316330336532386233303231333166396634643933373762646334663134
36616463393538323734613662396165646431646633303632343037656232306366623966386631
65313833616661616638386330393164316136333233643064326365343838663438313765663935
38396262623762343362373030323366313731376361666131336436666662643632326361643737
63353731393735376266633731373031323937633237393431323235373164366139383763343764
39336430626435373632613632623334366233333433393339383361623434383333633363336133
65396232656336353866346338393539363636613637363663353764333261633538323561633265
62353738353935653936616162313837346261353965363037383338626261636339633463326537
64623763643832306363303666613563316362643866323730656231623935333734386435643339
32386364626239343864623838616465376331393439396330353732313237313933363034323439
61346664363632643137383162313661303336313234376461373662643064373766636439616165
37346161636663356434643239653130343135653134353136346662333762626265306232333931
33313834653861376230643865613438306232636564366663373063353032333761326633353831
35376436666133363362386530366639303430613137323337383839306132626166613961383864
31373935333130383230613838353165303137363939323465656535646261636634656463626534
30646634623234643731623362356664333031633766336630323534316135323237323032333131
62333032376665373462386635336133303030313966646164376539666334366239366166623535
31646134643030373664346262336532653035336236633464326132383934353532653364623630
61626337333366393133623931343434623832633731363039313233663339326239666333373261
64373231343866646436626264383835383832353266623165653736626132373864316432373663
32376265333661383663343736363233343038643632666462343135666561653436343531353461
36346339666263333266313831373962376230383232633135303936636535313734363362646331
65356631373234633163333538333365343933626233663337353839366339393161323566376636
37653265363964363565303761623961356433393662386261623831663234656636626230386637
32616161343031643335353366656262663561323633333935613735303433613433386238313966
35653837636232623037353662613163616565373736396433386463396536663933373737343137
33326562323634626139393833326363623038343266396433346161646637383962326565633732
63636565383465653865633735363964653432336466306165336334613139303765313338356566
62666338393264306131633533356364376336636632356263626561323964333563343663343432
33336363623136393535653132346339616638663330643039356237386430336163363333643166
64343764623462366364343136306264313265356132313730626265313239366436326563326235
64323933343730626133303464356237663061353563336238353634376363316139656464343165
61353437346562316363303164303765346636363836656438613130333532383134386433326538
37626463633237653433333534386330356261613038653130363264383538323265303363663531
38613238356333303036616465363837313362373930646432343534626363363766386265616264
36366332353561656461383939343431633039363937363333653531373264343537623135643633
36373938373962643432323365303663623932643232356434383564373939616334363134366536
61313437366431323463336233373935346430363534323738633235333262326139306561323534
38313263633837666133613737313831366335386262396262633636623866636633376237373433
62383566663565323332656564393863666565333561346532353262386636626239363139306431
65306437336532613233626233666536626430303537376333623263386265313162323530313836
36303262353862663531613833633364303466343334336535386466666137386630383134396461
31623630383136333135333030396364653539386135653435353462646564656631323163316564
33376163363838303335346632613135333531343037396136363864343265313062623039376663
65656237656364313336343161336364393139643637363764336136343865613664396132353730
63366432356136313036626331636236396539633032383036323964643436666639616364343534
30313865636236363633343439653166636364353333643862353865373436656339306262636161
31633330643561343538353537383731313930323038626630366433393832383331313735646233
39343439363033393933623862343531393334336133616438653062386265643138386330316531
39353136363939373034313731333737353062393231396162343563393834656534326334623132
31303133643663323235336539303563383435343730336632393835393761653939346665666262
66336139346634633761343266343262373632623138646439343462626562383963626133303032
62396365383836626535366632373137386361343438373839373930373931316338643637353135
63656534396234333965306238316230386237633462643132373032643833396233376461656234
38396563623334613936376361323466303830363363613266666135396236646636393764313666
65353761356436353830373561396263376332383366393839306234313465643665346534353431
33366431613332343231633531623365383936666262323333646534343535393532666561653633
66363835623835313536616231343232366437373961363634323538343166313735666431633537
63363234326436343961313537323261333634643437373063666564333764633132323336666663
66393663373436666234333135326137303562666566373331336661633038303764643837313430
38326464336135386636316337313261656362643534346564356661623965336636333761646564
35383762396262633535323130333930303534306363656438356664633138346166646561626561
62396238623339323862303365303536396166353762333530333638306333383564363363626237
6162646361333635336264363265363066643932623133366532
