$ANSIBLE_VAULT;1.2;AES256;user
38376535386138636463636234393961396132363663356461656534373839663663646434633435
3431356662353565343965636433326136646632336135320a633663666362306134663235613463
61363639653531373638323563633331376166666364646432303136386638386165646433613936
6535366566336636380a356432366263653965393065663235323939313130366439393931346135
64336265646230613431333966383165343963613562633331326131613863626564613137616462
61353037616336663433313863336232633930376561303630313461343264346531346664633663
33636463626538653765373266303761343031653164623135633533326366663631396632323837
34386163323536356533333338323430633361313935336161346631613131373032336364633434
65316138353666636566303733353434396166316665623639376364366562373566383339316432
36636638396238626430613036386165343636663739333165643262333764386366383532313533
64346536386631653763336238303331356239336636663863656238323764393165383834303638
63376566313231363663313738346131336132373261633534383166356534363964363637383033
61613932303363316264646636356133313336643861323265333766316164323231303932636435
62623431363939323539623731383861646436666261303839396561353534306263653931666639
64373035306466656262326131646135636562613932353537346532636463396665356631323234
65613431323164353630393336653733363462663661313465346562333233656265303764626134
31323763656230343737326466313533613262303531623364313032333133646334663731623935
62343731363538343161333964343038323832623034353539653866306336343832336637633663
30386335363433333765353135333434366434656536326236633230623133386264343837383062
61663435373539336637323435616336666437303561303532383731333432383366656636616466
63636239363739363730303833336433333030373661623362646135613063393733323264373130
30613861356530663762633433633365663034633330356537393739396161396462376239366664
30376637306236353436616430383464623036643230643730313434306263323431343139613531
30613231383666643163663065346335376364396238333434303761386235376232646631613834
65353039383338633239316366313332383265663134613961363335393139616466613438383561
33366633343065656565626432663331333130623230613834653662386434323864323866646233
34316631366134356161663339663034376166653937346237616365316334626363633062646533
65383665663735636632653239386664643336326335366364613962623335346364666263646332
64323130656132343732393566316530373132373533333439616138383237653936353863633437
66353961613734613135623836386337613161396134613164643139353339386464643334623135
35666637383337383633353662663530343231336161623634366164633837393331366337386532
32356135366163666466623531356138353137313039623861316161346234613766626137633635
66366535376561633236353031656264616232623366373931306461396136373034343164663362
38376437653235623436633333326333303832653630363633303333623031366436343661656438
66313236623735376564663533656163373862636562653333623439643063663261633239343166
33393535313333643463313862353933636432336535303834343064383961633863386436643733
38323639346139313534623263653064313839646136333839313862306338613963396161646363
61366236656133613435393831383835643234373463356538643435636230396236616536386264
32313133633233616432616332393939633633306134303531643064396639326362653534333037
65303935313639643237326661316431383335313035343839343234386437383934303565323566
61643362623063616262373330316566363065336665623732643038613339333865646431613932
66303166303639306235656438636334343931646539663534366437356536303334653666333431
62333262613230313431366234643435626261333335373030663364333330313233366130666662
38323732623666363962353764653732323933393065333137353665623235336666626162363935
31316631386434633534613833353162353237363863303930656330333065613362383833653763
62636130363430333839323563333138353932353336386431363135376564326339313165396530
32323339643362313534393765343462633337373666653136313336646634333462656463633466
35303161306532626139643961633761313539376565306534393266626638663039653161633232
30393339343535613062396636366464393536393765626136336130383665356662326634313737
31383232666639363062306135336136303665653735666462653635366264323434343531383335
30396633383932653230326264316361353762353162316436666334323662326463613665626263
35313735336537383031353864636662323436386136366332326332326334663963336535353366
38653966383163343531366366656434336264303835386161373766323363663464663565313234
32643036373832353566663433343932366134613134383962373033346133383935323963323533
65343563633233313336323032633464666532346563313065313464323930376336336537646431
63666263303433373930353266363330386136303566363437663839626238316130646135633337
64386664663065653633383639356531363230663339626637373064373435373630643939316536
37656538313531346564363265656138653038343233363935333138383062633762636638396434
65623664626461663430356139656665623435623766333934666464396366376566663037643134
61333265343033363831353432343736313035633936323138343664373534643365616537376139
34343865313537663937643932306261386165386130343763663262326434376362653861386432
62346133316262356330326333623630623132643762343230316333353061653162323166353161
34363534663337633938303730636363386136306233616539333766383961393535626361316130
64383732623338373136633663636635336631333662313838393866336430323830363063373339
66666264613333363931626666313232333132613238623632613466303432316430363330376535
38396536313336343330386166656562396163633730626262343166303235663335376534363261
32343464356166643063623463386331633432383537346636653233373737326633643031646565
65303634303637316362396530363766333635373966623438623335653566333232386664376435
31336231346638646461396431396234326230316637313531383934383363336365356563626534
65313137376666323066656139326530643136313933636232336364323366393563323163373665
33356531646461313634306535386532323935623962633466373531353366303766366535303838
37386162623631643036313734333566616639633939383233303363343464663466363931353062
64333530653763356163353634326630633664646335343363656530333734393232353432616464
35333737396138663030393237323632636465306461623961333739313930623332323534396539
33623934346666323932386464613462346563636630393837303033666439376163313531633663
39366663613462663763313438353933353938343863643535616631666461373266333963663938
39366538393163663638653839323766616361393932323335626139353334383466383838343939
37393664646466653761346636303836326564313937666237343361366335616137383634643862
65343663393834393466346536663466646563313934336562313265306435303862643730343730
33313765343234383235353630663532633531313333333063303435623732616430353635306264
34316431333661626362646166313133376137396133663865643739326163623736336131353330
33653735613936326464626330373461333136613838333132653464656439656633363938376135
62313838353933633633396139663734393837623561353036393032303561313732326139636463
65643534633334373066366238616362366233633031353534363132303137396161656230316161
33613635323863373066373361626537613732396434396437343166356233373530323565333938
32363437343566643430383331396661393133353663353736353039396637343939333036393365
37613862646533303235333237303931386164383333656363666136656337386236383538366634
66393130313134363336323833323233366133633230393431616463616436386665373632616131
35653464313264316638313130336337383835656266386132616463333535343732626131653834
34313039356337303834373636366532396536666537326638333065616138653036323436366138
36663536303037353737303536383863623234303939366431326535636261376539346635323738
63373566316131653762646462373861373938323461653166626631336435313461353430653664
65656664343832613765393639653064323762376432366264653131626235656363316138366165
32646565363635396331306263643639653835343332666566313365393463653332316163373861
39633134353639656462626163363431366334323665633632656462653961656436373033346535
33393238373239376639313062366632323039346138346465366562313230376332373262363836
64396538653761323361633562663732343665366263346262326139363465636564363165346430
63613137303336653232383032663033313430383335653661616263313933643763333464643231
66623830303636326437636130316237373834633339303962356131633763333265353166636465
61623535373733613139613932663732303664613363626238313766653533313663316338633233
34373839346463663335653732666362626535613534323534366666326138333034336230373764
66633830393163376635346237333564366533633263346663356439636135343865393633653365
32396661646332623964303238613833326563353132303230343133353139313762666532346338
32633930636130316462373034396636383037646631353036646462303562653830306431353734
31323638646363376166643465383737656663346232636666323464386464383566326365326335
38383538616333333261666130623363366163626366363962323535383661633262616535393661
63336537643737353031626432353966343438326636636135373862393564376538656464626436
36353532396633366339633563383834343237303164346439313634306162396239356532353138
63303938326331643661383034323438346334633363623132356530393236353966303061646131
38616565343336303162303131326430393234313234303261303130353039613731346238356235
38313035373037393931656238643830373534303833653837356539303031356234313264356463
39396237666465393037616238366366326538396536386265366537313331663539366233643532
30373064643231613431666539316566646438663038643665633437333837636339373262666236
38386438303732363165383232616535336261626538383363313133613732623632346662356632
34653433353335336532373439643836396230326139333437666539356233306165393363393163
38323965346536306639376332636438653837663437303636323139313063353539633163356363
31326434656435353634323532343134393032613866626237623133373538336665366132323734
62623036623030343363313764396635363636613965303535343262393835663538613065663933
38613238383836346135643735353333343461333336376438373734386334663563363430633362
34353430386231393930613161333032306339356139356661613435666238626432616533393938
63396262613637316138333531636138643665616436353038653736343930643238613137623931
30353231363631366564363365353066623432613936396231653935333135356162313335613464
63633232336364313737616561643265373838323633336164643064316638303238323062383864
61366631633838616461343664656633373534373764373962316262323931323237306134303461
31373836316533366638363363646530623335356537303033373235353634623833633662346466
64623236393764356633383232326162313930633437636230383230353336626263383565633632
30663265663265316131646162373739653131383662303665653334383436646165636535306162
30313665633764383236376462323431303836356432626232363837656339623462363764626234
63313766636634316363303262366337306563666533396233393939613635356538393363666438
66333536393535323032333735333166626639313237323731386632646331303831386434373562
64383839303636663135333137663230376562366535656361336133653034323866633838373934
36333432653336623062366636633931613266336131646462636665616266616164363334333466
6239
