- name: Configuration default
  ansible.builtin.template:
    src: default/sample
    dest: /tmp/sampleTemplateAnsible
  register: default_result
  ignore_errors: true

- name: Configuration specific
  ansible.builtin.template:
    src: sample
    dest: /tmp/sampleTemplateAnsible
  when: default_result.failed
