---

- name: Update DNS
  ansible.builtin.include_role:
    name: update_infomaniak_dns
  vars:
    update_infomaniak_dns_target_extension: '{{ redmine.domain.suffix }}'
    update_infomaniak_dns_target_ip: '{{ ansible_default_ipv4.address }}'
  when: not redmine_unsecured

- name: Install redmine pre requisites
  ansible.builtin.apt:
    name:
    - curl
    - gnupg2
    - libcurl4-openssl-dev
    - libmagickwand-dev
    - postgresql-client-{{ postgresql.version }}
    - postgresql-server-dev-{{ postgresql.version }}
    - imagemagick
    - git
    state: present

- name: Is already installed ?
  ansible.builtin.stat:
    path: "/opt/redmine/config/database.yml"
  register: already_installed

- name: Is already downloaded ?
  ansible.builtin.stat:
    path: '/tmp/redmine-{{ package.version }}.{{ package.type }}'
  register: already_zip

- name: Create dedicated database
  ansible.builtin.include_role:
    name: pg_new_fresh_database
  vars:
    pg_new_fresh_database_pg_username: '{{ dbschema.redmine.username }}'
    pg_new_fresh_database_pg_password: '{{ dbschema.redmine.password }}'
    pg_new_fresh_database_pg_database: '{{ dbschema.redmine.database }}'
  when: not already_installed.stat.exists is defined or not already_installed.stat.exists

- name: adding gpg key for rvm mpapis
  ansible.builtin.shell: set -o pipefail && curl -sSL https://rvm.io/mpapis.asc | gpg --import -

- name: adding gpg key for rvm pkuczynski
  ansible.builtin.shell: set -o pipefail && curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

- name: check is rvm already installed
  ansible.builtin.stat:
    path: /usr/local/rvm
  register: rvm_exists

- name: install rvm
  ansible.builtin.shell: set -o pipefail && curl -sSL https://get.rvm.io | bash -s stable
  when: not rvm_exists.stat.isdir is defined or not rvm_exists.stat.isdir

- name: Adding user root to rvm users
  ansible.builtin.user:
    name: 'root'
    groups:
      - 'rvm'
    append: yes

- name: Check if nginx already exists
  ansible.builtin.stat:
    path: /opt/nginx/sbin/nginx
  register: nginx_exists

- name: Install ruby {{ ruby.version }}
  ansible.builtin.shell: /usr/local/rvm/bin/rvm install {{ ruby.version }}

- name: Use ruby version {{ ruby.version }}
  ansible.builtin.shell: /usr/local/rvm/bin/rvm alias create default ruby-{{ ruby.version }}

- name: Install pg client
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; gem install pg -v '{{ package.gems.pg }}'

- name: Install passenger
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; gem install passenger -v '{{ package.gems.passenger }}'
  when: not nginx_exists.stat.exists

- name: Install nginx with passenger
  ansible.builtin.shell: passenger-install-nginx-module --auto --auto-download --prefix=/opt/nginx --languages ruby
  environment:
    GEM_PATH: '/usr/local/rvm/gems/ruby-{{ ruby.version }}:/usr/local/rvm/gems/ruby-{{ ruby.version }}@global'
    GEM_HOME: '/usr/local/rvm/gems/ruby-{{ ruby.version }}'
    PATH: '/usr/local/rvm/gems/ruby-{{ ruby.version }}/bin:/usr/local/rvm/gems/ruby-{{ ruby.version }}@global/bin:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin'
  when: not nginx_exists.stat.exists

- name: Rvm group for rubies folders
  ansible.builtin.shell: chown -R root:rvm /usr/local/rvm/rubies

- name: Add mjs extension to javascript files
  ansible.builtin.lineinfile:
    dest: /opt/nginx/conf/mime.types
    insertafter: '^\[Service\]'
    regexp: '    application/javascript.*'
    line: '    application/javascript                           js mjs;'
  when: not nginx_exists.stat.exists

- name: Ensure group "redmine" exists
  ansible.builtin.group:
    name: redmine
    state: present

- name: Add the user 'redmine'
  ansible.builtin.user:
    name: redmine
    group: redmine

- name: Adding user redmine to rvm users
  ansible.builtin.user:
    name: 'redmine'
    groups:
      - 'rvm'
    append: yes

- name: Backup old installation, if needed
  ansible.builtin.copy:
    remote_src: true
    src: '/opt/redmine/config/{{ item }}'
    dest: '/opt/{{ item }}'
  ignore_errors: true
  register: ignore_errors_register
  loop:
    - 'configuration.yml'
    - 'database.yml'
  when: already_installed.stat.exists is defined and already_installed.stat.exists

- name: Cleanup target folder
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
  - '/opt/redmine-{{ package.version }}'
  - '/opt/redmine'

- name: Download redmine files
  ansible.builtin.get_url:
    url: https://www.redmine.org/releases/redmine-{{ package.version }}.{{ package.type }}
    dest: /tmp/redmine-{{ package.version }}.{{ package.type }}
    checksum: sha256:{{ package.checksum.sha256 }}
  when: not already_zip.stat.exists is defined or not already_zip.stat.exists

- name: Extract redmine files into /opt
  ansible.builtin.unarchive:
    src: /tmp/redmine-{{ package.version }}.{{ package.type }}
    dest: /opt
    remote_src: 'yes'
    owner: 'nobody'
    group: 'rvm'
    mode: '775'

- name: Link to current version
  ansible.builtin.file:
    src: /opt/redmine-{{ package.version }}
    dest: /opt/redmine
    state: 'link'
    owner: 'nobody'
    group: 'rvm'

- name: Copy database configuration file
  ansible.builtin.template:
    src: database.yml
    dest: /opt/redmine/config/database.yml
    owner: 'nobody'
    group: 'rvm'
    mode: '0644'
  when: not already_installed.stat.exists is defined or not already_installed.stat.exists

- name: Copy mail configuration file
  ansible.builtin.template:
    src: configuration.yml
    dest: /opt/redmine/config/configuration.yml
    owner: 'nobody'
    group: 'rvm'
    mode: '0644'
  when: not already_installed.stat.exists is defined or not already_installed.stat.exists

- name: Restore old configuration, if needed
  ansible.builtin.command: mv /opt/{{ item }} /opt/redmine/config/{{ item }}
  loop:
    - 'configuration.yml'
    - 'database.yml'
  ignore_errors: true
  register: ignore_errors_register
  when: already_installed.stat.exists is defined and already_installed.stat.exists

- name: Configure bundle tools
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; bundle config set --local without 'development test'
  args:
    chdir: '/opt/redmine/'
  become_user: redmine

- name: Configure redmine user to retrieve gems
  ansible.builtin.shell: chmod -R g+w /usr/local/rvm/rubies/ruby-{{ ruby.version }}/lib/ruby/gems/{{ ruby.reducedversion }}

- name: Retrieve dependencies for redmine
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; bundle install
  args:
    chdir: '/opt/redmine/'
  become_user: redmine

- name: Generate redmine token
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; bin/rake generate_secret_token
  args:
    chdir: '/opt/redmine/'
  become_user: redmine

- name: Migrate redmine database
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; RAILS_ENV=production bin/rake db:migrate
  args:
    chdir: '/opt/redmine/'
  become_user: redmine

- name: Directory for files under /data
  ansible.builtin.file:
    path: /data/redmine-files
    state: 'directory'
    owner: 'nobody'
    group: 'nogroup'

- name: Directory for logs
  ansible.builtin.file:
    path: /var/log/nginx
    state: 'directory'

- name: Remove default files directory
  ansible.builtin.file:
    path: /opt/redmine-{{ package.version }}/files
    state: 'absent'

- name: Link to data directory
  ansible.builtin.file:
    src: /data/redmine-files
    dest: /opt/redmine-{{ package.version }}/files
    state: 'link'
    owner: 'nobody'
    group: 'nogroup'

- name: Permission to tmp directory
  ansible.builtin.file:
    path: /opt/redmine-{{ package.version }}/tmp
    state: 'directory'
    mode: '777'
    owner: 'nobody'
    group: 'nogroup'
    recurse: true

- name: Install nginx service script
  ansible.builtin.copy:
    src: nginx.service
    dest: /etc/systemd/system/nginx.service
    owner: root
    group: root
    mode: '0644'

- name: Copy minimal nginx configuration file
  ansible.builtin.template:
    src: minimal.conf
    dest: /opt/nginx/conf/nginx.conf
    owner: 'nobody'
    group: 'nogroup'
    mode: '0644'

- name: Create external configuration for nginx
  ansible.builtin.file:
    path: /opt/nginx/conf/server
    state: 'directory'
    mode: '0755'

- name: Nginx service reload/start
  ansible.builtin.systemd:
    name: 'nginx'
    daemon_reload: true
    state: started
    enabled: true

- name: Generate redmine certificate
  ansible.builtin.shell: /usr/bin/certbot certonly -d {{ redmine.domain.suffix }}.{{ server.domain.sub }}{{ server.domain.main }} -m {{ server.domain.contact }} --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html --keep-until-expiring --non-interactive
  when: not redmine_unsecured

# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  ansible.builtin.template:
    src: redmine.conf
    dest: /opt/nginx/conf/server/redmine.conf

- name: Nginx service restart with full configuration
  ansible.builtin.systemd:
    name: 'nginx'
    state: restarted

- name: Logrotate configuration
  ansible.builtin.copy:
    src: logrotate
    dest: /etc/logrotate.d/redmine

- name: Cleanup installation
  ansible.builtin.file:
    path: '/tmp/redmine-{{ package.version }}.{{ package.type }}'
    state: 'absent'
