---

- name: Install backup pre requisites
  ansible.builtin.apt:
    name:
      - jq
    state: present

- name: Backup folder creation
  ansible.builtin.file:
    path: '/backup'
    state: 'directory'
    mode: '0777'

- name: Copy backup script
  ansible.builtin.template:
    src: backup.sh
    dest: /opt/backup.sh
    owner: root
    group: root
    mode: '0700'

- name: Copy backup service
  ansible.builtin.copy:
    src: backup.service
    dest: /etc/systemd/system/backup.service
    owner: root
    group: root
    mode: '0644'

- name: Copy backup timer
  ansible.builtin.copy:
    src: backup.timer
    dest: /etc/systemd/system/backup.timer
    owner: root
    group: root
    mode: '0644'

- name: Backup service enabling
  ansible.builtin.systemd:
    name: 'backup.timer'
    enabled: true
