---

- name: Update DNS
  ansible.builtin.include_role:
    name: update_infomaniak_dns
  vars:
    update_infomaniak_dns_target_extension: '{{ ethercalc.domain.suffix }}'
    update_infomaniak_dns_target_ip: '{{ ansible_default_ipv4.address }}'
  when: not redmine_unsecured

- name: Ensure group ethercalc exists
  ansible.builtin.group:
    name: ethercalc
    state: present

- name: Add the user ethercalc
  ansible.builtin.user:
    name: ethercalc
    group: ethercalc

- name: Download ethercalc files
  community.general.npm:
    name: ethercalc
    global: true
    state: present

- name: Install ethercalc service script
  ansible.builtin.copy:
    src: ethercalc.service
    dest: /etc/systemd/system/ethercalc.service
    owner: root
    group: root
    mode: '0644'

- name: Ethercalc service reload/start
  ansible.builtin.systemd:
    name: 'ethercalc'
    daemon_reload: true
    state: started
    enabled: true

- name: Generate ethercalc certificate
  ansible.builtin.shell: /usr/bin/certbot certonly -d {{ ethercalc.domain.suffix }}.{{ server.domain.sub }}{{ server.domain.main }} -m {{ server.domain.contact }} --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html --keep-until-expiring --non-interactive
  when: not redmine_unsecured

# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  ansible.builtin.template:
    src: ethercalc.conf
    dest: /opt/nginx/conf/server/ethercalc.conf
    owner: root
    group: root
    mode: '0644'

- name: Nginx service restart with full configuration
  ansible.builtin.systemd:
    name: 'nginx'
    state: restarted
