---

- name: Install package
  ansible.builtin.apt:
    name:
    - fail2ban
    state: present

- name: Active nginx supervision
  ansible.builtin.copy:
    src: customNginx.conf
    dest: /etc/fail2ban/jail.d/customNginx.conf
    mode: '0644'

- name: Default backend set to systemd
  ansible.builtin.lineinfile:
    dest: /etc/fail2ban/jail.conf
    regexp: "^backend = auto"
    line: "backend = systemd"

- name: Modify rights access to allow netdata supervision
  ansible.builtin.shell: chmod o+r /var/run/fail2ban/fail2ban.sock

- name: Service restart
  ansible.builtin.systemd:
    name: 'fail2ban'
    state: restarted
